In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn import svm
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
df=pd.read_csv("C:\\Users\\ankit\\Documents\\Project Files\\Spam email.csv")
df.head()

Label                                          EmailText
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
labe=LabelEncoder()                                      # spam = 1
df['Label']=labe.fit_transform(df['Label'])              # Ham = 0


In [4]:
df.head()

Label                                          EmailText
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [5]:
X=df['EmailText'] 
y=df['Label']
print(X,y)

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568               Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: EmailText, Length: 5572, dtype: object 0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: Label, Length: 5572, dtype: int32


In [6]:
# train and test splitting of data
X_train,y_train=X[:2000],y[:2000]
X_test,y_test=X[2000:],y[2000:]

In [7]:
cv=CountVectorizer()    # it used to converting string data inta float data for further preduction
X_train=cv.fit_transform(X_train)
X_test=cv.transform(X_test)

In [8]:
X_train[:5]

<5x4973 sparse matrix of type '<class 'numpy.int64'>'
	with 64 stored elements in Compressed Sparse Row format>

In [9]:
rfc=RandomForestClassifier(n_estimators=200)
rfc.fit(X_train,y_train)
predict_rfc=rfc.predict(X_test)

In [10]:
print(classification_report(y_test,predict_rfc))
print(confusion_matrix(y_test,predict_rfc))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98      3105
           1       0.99      0.74      0.85       467

    accuracy                           0.96      3572
   macro avg       0.98      0.87      0.91      3572
weighted avg       0.97      0.96      0.96      3572

[[3101    4]
 [ 122  345]]


In [11]:
model=svm.SVC()
model.fit(X_train,y_train)
predic_svm =model.predict(X_test)

In [12]:
print(classification_report(y_test,predic_svm))
print(confusion_matrix(y_test,predic_svm))

              precision    recall  f1-score   support

           0       0.97      1.00      0.99      3105
           1       0.99      0.82      0.90       467

    accuracy                           0.98      3572
   macro avg       0.98      0.91      0.94      3572
weighted avg       0.98      0.98      0.97      3572

[[3101    4]
 [  84  383]]


In [13]:
mlpc=MLPClassifier(hidden_layer_sizes=(8,8,8),max_iter=400)
mlpc.fit(X_train,y_train)
predic_mlpc = mlpc.predict(X_test)

In [14]:
print(classification_report(y_test,predic_mlpc))
print(confusion_matrix(y_test,predic_mlpc))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98      3105
           1       0.98      0.73      0.84       467

    accuracy                           0.96      3572
   macro avg       0.97      0.87      0.91      3572
weighted avg       0.96      0.96      0.96      3572

[[3098    7]
 [ 125  342]]


In [15]:
accu_rfc=accuracy_score(y_test,predict_rfc)
accu_svm=accuracy_score(y_test,predic_svm)
accu_mlpc=accuracy_score(y_test,predic_mlpc)
print(accu_rfc,accu_svm,accu_mlpc)

0.9647256438969765 0.975363941769317 0.9630459126539753


In [16]:
import pickle
with open('model pickle','wb')as f:             ### Creating a model pickle file
    pickle.dump(predict_rfc,f)                    # wb is write in binary

In [28]:
with open('model pickle','rb')as f:          # rb is read in binary
    mp =pickle.load(f)

In [29]:
print(classification_report(y_test,mp))
print(confusion_matrix(y_test,mp))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98      3105
           1       0.99      0.74      0.85       467

    accuracy                           0.96      3572
   macro avg       0.98      0.87      0.91      3572
weighted avg       0.97      0.96      0.96      3572

[[3101    4]
 [ 122  345]]


In [30]:
import pickle
pickle.dump(model, open("spam.pkl", "wb"))      ## here model is for svc model testing

In [31]:
loaded_model = pickle.load(open("spam.pkl", "rb"))
loaded_model.predict(X_test)
loaded_model.score(X_test,y_test)


0.975363941769317

In [43]:
import nltk  ## Preprocessing our text
from nltk.corpus import stopwords ## removing all the stop words
from nltk.stem.porter import PorterStemmer 
import re
def new_review(new_review):
    new_review = new_review
    new_review = re.sub('[^a-zA-Z]', ' ', new_review)
    new_review = new_review.lower()
    new_review = new_review.split()
    ps = PorterStemmer()
    all_stopwords = stopwords.words('english')
    all_stopwords.remove('not')
    new_review = [ps.stem(word) for word in new_review if not word in   set(all_stopwords)]
    new_review = ' '.join(new_review)
    new_corpus = [new_review]
    new_X_test = cv.transform(new_corpus).toarray()
    new_y_pred = loaded_model.predict(new_X_test)
    return new_y_pred
new_review = new_review(str(input("Enter new review...")))
if new_review[0]==1:
    print("SPAM")
else :
    print("NOT SPAM")

Enter new review...FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, å£1.50 to rcv
NOT SPAM
